version: '4.0'

services:
  mysqldb:
    image: mysql:latest
    container_name: spring_cloud_demo
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demoapp
      - MYSQL_PASSWORD=demoapp