DROP TABLE IF EXISTS todo;
CREATE TABLE todo (id SERIAL PRIMARY KEY, description VARCHAR(255), details VARCHAR(4096), done BOOLEAN);

INSERT INTO todo VALUES (1, 'MY FIRST PROJECT', 'GENERATING SPRING BOOT AZURE PROJECT', TRUE);
INSERT INTO todo VALUES (2, 'MY SECOND PROJECT', 'GENERATING SPRING BOOT DOCKER COMPOSE PROJECT', FALSE);
INSERT INTO todo VALUES (3, 'MY THIRD PROJECT', 'GENERATING SPRING BOOT AZURE KEY VAULT PROJECT', FALSE);